name:                djambi
version:             0.1.0.0
github:              "githubuser/djambi"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

default-extensions:
- OverloadedStrings
- TypeOperators
- DataKinds

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/djambi#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- http-types
- servant
- servant-server
- text
- wai
- warp

library:
  source-dirs: src

executables:
  djambi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - djambi

tests:
  djambi-test:
    main:                test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - djambi
    - hspec
    - hspec-discover
    - hspec-wai
    - QuickCheck
